name: Proton valvexbe sniper container

on:
  schedule:
    - cron:  '45 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          export CARGO_HOME="$PWD"
          rustup target add i686-unknown-linux-gnu
          cd proton-tkg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/_no_container="true"/_no_container="false"/' proton-tkg.sh
          echo '_ci_build="true"' >> proton-tkg.cfg
          touch tarplz
          yes|./proton-tkg.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
