name: Wine Arch Linux NTSYNC CI

on:
  workflow_dispatch:
  push:
    tags:
      ["v[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2 git vulkan-headers

      - name: Create User
        run: |
          useradd -m -G wheel -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Build and Install ntsync-header from PKGBUILD
        run: |
          sudo -u user bash -c "
            cd ~
            git clone https://aur.archlinux.org/ntsync.git
            cd ntsync
            makepkg -si --noconfirm
          "

      - name: Compilation
        env:
          XDG_CACHE_HOME: /tmp/.cache
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo
          cd wine-tkg-git
          ./xiv-setup.sh -S v10.5
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-arch
          path: wine-tkg-git/non-makepkg-builds