name: Wine Arch No lsteamclient CI

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+-nolsc", "v[0-9]+.[0-9]+.[0-9]+-nolsc"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ntsync header
        run: |
          ntsync-header/install-header.sh

      - name: Compilation
        env:
          XDG_CACHE_HOME: /tmp/.cache
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo jack lib32-jack2
          cd wine-tkg-git
          ./xiv-staging.sh -lS v10.16
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-arch-nolsc
          path: wine-tkg-git/non-makepkg-builds
