name: Wine Valve exp bleeding edge CI

on:
  workflow_dispatch:
  push:
    tags:
      "valvebe-[0-9]+-[0-9]+"
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          sudo apt install libxkbregistry0 libxkbregistry-dev
          cd wine-tkg-git
          sed -i 's/pkgname=wine-tkg/pkgname=unofficial-wine-xiv/' non-makepkg-build.sh
          sed -i 's/LOCAL_PRESET=""/LOCAL_PRESET="valve-exp-bleeding"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          for f in wine-tkg-userpatches/valvexbe/*.patch; do mv "$f" "wine-tkg-userpatches/$(basename ${f%.patch}).mypatch"; done
          for f in wine-tkg-userpatches/valvexbe/*.revert; do mv "$f" "wine-tkg-userpatches/$(basename ${f%.revert}).myrevert"; done
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-valvexbe
          path: wine-tkg-git/non-makepkg-builds
