name: Wine Fedora lsteamclient CI

on:
  workflow_dispatch:
  push:
    tags:
      ["v[0-9]+.[0-9]+", "v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:41

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          cd wine-tkg-git
          ./xiv-setup.sh -S v10.12
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-fedora
          path: wine-tkg-git/non-makepkg-builds