name: Wine Valve exp bleeding edge CI

on:
  workflow_dispatch:
  push:
    tags:
      "valvebe-[0-9]+-[0-9]+"
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          sudo apt install libxkbregistry0 libxkbregistry-dev libswresample4 libavcodec60 libavutil58 libncurses-dev libfreetype-dev
          cd wine-tkg-git
          ./xiv-setup -v -V dc36da83d0c0bb3afce07cdcb1c5621013f50dc2
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-valvexbe
          path: wine-tkg-git/non-makepkg-builds
