name: Wine Fedora No lsteamclient CI

on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+-nolsc", "v[0-9]+.[0-9]+.[0-9]+-nolsc"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:41

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ntsync header
        run: |
          sudo ntsync-header/install-header.sh

      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          cd wine-tkg-git
          ./xiv-staging.sh -lS v10.16
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-fedora-nolsc
          path: wine-tkg-git/non-makepkg-builds
