name: Wine Ubuntu lsteamclient CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          sudo apt install libxkbregistry-dev
          cd wine-tkg-git
          sed -i 's/pkgname=wine-tkg/pkgname=wine-xiv-lsc/' non-makepkg-build.sh
          sed -i 's/_wayland_driver="false"/_wayland_driver="true"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/-W ntdll-NtAlertThreadByThreadId/-W ntdll-NtAlertThreadByThreadId -W vcomp_for_dynamic_init_i8/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          echo '_lsteamclient_patches="true"' >> customization.cfg
          for f in wine-tkg-userpatches/*.lsc; do mv "$f" "wine-tkg-userpatches/$(basename ${f%.lsc}).mypatch"; done
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-lsteamclient
          path: wine-tkg-git/non-makepkg-builds